### ISSUE TITLE
Use well-known public licenses to license from employee to company?

### ISSUE THREAD

**Issue by kemitchell** [github/balanced-employee-ip-agreement#46]
Issue ahead of a possible PR.

Current section 3 reads:

> **Contribution of your IP to Company projects.** If you include your own IP – such as IP you created prior to working for the Company – into a Company product or service, it's still yours, of course, but you grant the Company a nonexclusive, irrevocable, fully paid-up, royalty-free, perpetual, sub-licensable, transferable, worldwide license to use it without restriction in any way or implementation, in modified form, or as is, by itself, or incorporated into another product or service ("License"). If you include your name in any project over which the Company would have rights under this Agreement, such as in a copyright notice or a comment in code or documentation, then the License covers the rights associated with that use of your name as well.

If the point is a completely permissive license---essentially waiver of exclusive rights against the company---why not license "your own IP" to the company under the terms of well-known form public licenses?

Setting other feedback I may have on section 3 as currently worded aside for the moment, consider:

> **Contribution of your IP to Company projects.** If you include your own IP – such as IP you created prior to working for the Company – into a Company product or service, it's still yours, of course, but you grant the Company a license to use it ("License"). _The terms of that license are those of The MIT License (as standardized by SPDX) for software, configuration, and other engineering work, and otherwise those of the Creative Commons Attribution 4.0 International license._ ...

(This is just a first stab.  If there's interest, I might propose different language in a PR.)

I see a few advantages to this approach:

1.  The usual license litany---nonexclusive, irrevocable,...---is a potent, magic-words sleep spell.  If the agreement wants to read plain, it'd do better without it.

2.  Even if the standard licenses use much the same kind of jargon, many folks have _experience_ with how they're used, and what they mean.  That being the case, referencing the jargon in a preexisting license isn't hiding the ball, but still cleans up the terms.

3.  There are extensive resources for not-so-lawyers about MIT, CC-BY-4.0, and their ilk.  For CC-BY, the authoring institution itself provides explainers.  MIT has been analyzed repeatedly, in print and online.

**Comment by mlinksva** [comment]
Interesting suggestion. We're all for using standard open source licenses where they make sense, but it isn't clear one would be a win here:

- It's doubtful that many companies are keen to take on keeping track of and providing license and copyright notices (which come with common permissive licenses) when these are so easily avoided by getting an unconditional license...
- ...somewhat common unconditional licenses (e.g., CC0-1.0, Unlicense) aren't nearly as well known and each have their own small problems
- Even if notice conditions were acceptable, common permissive licenses such as MIT are only well understood in the context of open source projects; using one to make a private (but non-exclusive) grant, and incorporating such through reference seems more confusing than short litany currently in the text (even more so since MIT and similar are templates, and Apache-2.0 is really long).

So closing this, but feel free to point out what we're missing if anything, or other solutions.

**Comment by kemitchell** [comment]
If there isn't any copyright notice in the agreement, there isn't any copyright notice to redistribute. Or, to be more explicit, reference MIT but follow with affirmative waiver of the attribution requirement.
