### ISSUE TITLE
New York State?

### ISSUE THREAD

**Issue by jasonfb** [github/balanced-employee-ip-agreement#51]
Can we put together a working group to evaluate if this BEIA if legally enforceable in New York State?

My understanding of NY State's (regressive) laws are that IP created by computer programmers is owned by the employer, onsite or offsite business location, on company property or on employee-owned property. 

So because of the regressive law, your BEIA will get thrown out by a NY State court. Can we think about this or address this?

I personally would like to start a NY-based advocacy group to lobby Albany to change our regressive laws. I am seeking others in NY State who would be interesting discussing this with me.

**Comment by jasonfb** [comment]
@hoolio, @jessephus, and @talniv -- as your list of state-based laws does not include New York, I'd love to hear your lawyer's thoughts on how to think about this in the context of a state like New York. I am also having this conversation with some IP lawyers who are more familiar with New York state laws to get their take on this.

**Comment by mlinksva** [comment]
Hi @jasonfb, thanks for posting this. First off, note the [project disclaimer](https://github.com/github/balanced-employee-ip-agreement/#disclaimer). Nobody is offering legal advice here. BEIPA is intended to work in any U.S. state, but you should indeed consult with your own attorney to evaluate whether it works for your situation.

In general, most of the state laws included in the exhibit limit what IP can be assigned to an employer. Agreements that assign more could be unenforceable, though they still might deter employees who don't know of the laws (presumably nearly all), which is why some of the laws also require that IP agreements come with notice of such laws (thus the exhibit). The absence of such statutory limitation doesn't mean an employer must claim everything, nor that an agreement that claims less (like BEIPA) is unenforceable.

I imagine we should add something to the README to make this more clear. I'll leave this open as a reminder to do so.

In terms of NY state reform, a few thoughts:

- Most of the state laws in the exhibit were enacted in the years following Minnesota's 1978 "freedom to create" law (the one [in the exhibit](https://github.com/github/balanced-employee-ip-agreement/blob/e8a2fe7d122035ce531fe0dd1297b351032dc82b/Balanced_Employee_IP_Agreement.md#minnesota)). It'd be interesting to see a 21st century take on such law, perhaps starting in NY. :smile:
- On the related (because it's about employee mobility) issue of non-compete reform, in the last year the NY AG has been [challenging broad non-competes](https://www.littler.com/publication-press/publication/ny-attorney-general-schneiderman-declares-%E2%80%9Cwar%E2%80%9D-non-compete-agreements). I haven't looked at recent legislative activity, but several states are considering reform, up to copying California's ban on most non-competes.
- Much more weakly related, and mostly symbolic due to the small amount, there's been a NY bill proposed since 2009 to provide a [$200 tax credit for open source development](https://opensource.com/government/16/3/ny-bill-tax-credit-open-source-contributors). I mention this here because it's another mechanism aligned with enabling more contributions to open source, and the people pushing for it might be informed about and sympathetic to reform more directly related to employment and IP and mobility.

**Comment by mlinksva** [comment]
The note I imagined adding to the README 3 years ago was already present! 😄 

> In some states with less employee-friendly law, BEIPA makes a bigger difference relative to the maximum employer control allowable by law often baked into employee IP agreements.
